import 'https://unpkg.com/aframe-environment-component@1.3.2/dist/aframe-environment-component.min.js'
import 'aframe-template-component'
import './components/AF_HtmlMesh.js'
//import 'super-hands'
// import 'aframe-glow'

import './components/orbit-controls/AF_orbitControls.js'
import './components/AF_Misc.js'
import './components/AF_axis.js'
import './aframe-data-cluster/AF_dataLoader.js'
import './aframe-data-cluster/AF_store.js'
import './aframe-data-cluster/AF_dataInjector.js'
import './aframe-data-cluster/AF_dataset.js'
import './aframe-data-cluster/AF_dataCrucible.js'
import './aframe-data-cluster/AF_dataCluster.js'
import './aframe-data-cluster/AF_globeComponent.js'
import './aframe-data-cluster/AF_dataChart.js'
import './aframe-data-cluster/AF_dataWall.js'
import './aframe-data-cluster/data-globe/AF_dataGlobe.js'
import './aframe-data-cluster/data-particles/AF_dataParticles.js'
import './aframe-data-cluster/data-particles/AF_dataWhip.js'
import './tests/AF_testShader.js'
// import './aframe-dev-components/AF_datgui.js'
